# Generated by Django 3.1.12 on 2025-03-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.CharField(max_length=255),
        ),
    ]
