# Generated by Django 3.1.12 on 2025-03-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20250304_1459'),
    ]

    operations = [
    ]
