# Generated by Django 3.1.12 on 2025-02-28 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField()),
                ('address_id', models.CharField()),
                ('method', models.CharField(choices=[('giaohangtietkiem', 'Giao hàng tiết kiệm'), ('giaohangnhanh', 'Giao hàng nhanh'), ('j&texpress', 'J&T Express'), ('ninjavan', 'Ninja Van'), ('viettlepost', 'Viettle Post')], default='giaohangtietkiem', max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
