# Generated by Django 3.1.12 on 2025-03-07 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20250307_1013'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='address_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='customer_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
